version: '3.8'

services:
  dbpostgresql:
    image: postgres
    container_name: postgresDatabase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=out-calories

  out-calories-core:
    image: out-calories/out-calories-core
    build:
       context: .
       dockerfile: ./out-calories-core/Dockerfile
       args: 
        JAR_FILE_PATH: ./out-calories-core/build/libs/*.jar
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql