-- liquibase formatted sql

-- changeset pznojek:init-000

-- create table

create table dbo_core.company_address (
	ID BIGINT generated by default as identity primary key,
	COMPANY_ID BIGINT not null references dbo_core.company(ID),
	COUNTRY VARCHAR(50) not null,
	ZIP_CODE VARCHAR(10) not null,
	CITY VARCHAR(50) not null,
	STREET VARCHAR(100),
	APARTMENT VARCHAR(20) not null
);