-- liquibase formatted sql

-- changeset pznojek:init-000

-- create table

create table dbo_core.meal (
	ID BIGINT generated by default as identity primary key,
	COMPANY_ID BIGINT not null references dbo_core.company(ID),
	NAME VARCHAR(255) not null,
	KCAL_AMOUNT int not null,
	PROTEINS int not null,
	CARBOHYDRATES int not null,
	FATS int not null,
	PRIZE numeric(6,2),
	CURRENCY varchar(3)
);